apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ecommapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ecommapp
    spec:
      containers:
      - name: ecommapp
        image: sibendudas/ecommapp
        ports:
        - containerPort: 3000
          name: svc-port
          protocol: TCP
        env:
        - name: ORDER_SERVICE_URL
          value: "http://orderservice:8080/order/"
---
kind: Service
apiVersion: v1
metadata:
  name: ecommapp
spec:
  type: NodePort
  ports:
  - name: svc-port
    port: 3000
    targetPort: 3000
    nodePort: 30300
  selector:
    app: ecommapp
